/*
 * Copyright (c) 2017, MegaEase
 * All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package main

import (
	"flag"
	"go/ast"
	"io"
	"os"
	"path/filepath"

	"github.com/dave/jennifer/jen"
	"github.com/megaease/easemeshctl/cmd/common"
)

type interfaceFileSpec struct {
	buf              *jen.File
	source           []*ast.TypeSpec
	writer           io.Writer
	pkgName          string
	resourceName     string
	generateFileName string
	sourceFile       string
}

func main() {

	var spec *interfaceFileSpec
	if len(flag.Args()) < 2 {
		spec = initialSpec()
	} else {
		spec = fromArgs(flag.Args())
	}

	err := newGenerator(spec).accept(nil)
	if err != nil {
		common.ExitWithError(err)
	}
	spec.buf.Save(spec.generateFileName)
}

func initialSpec() *interfaceFileSpec {

	spec := interfaceFileSpec{}
	// Get the package of the file with go:generate comment
	goPackage := os.Getenv("GOPACKAGE")
	spec.buf = jen.NewFile(goPackage)
	spec.buf.PackageComment("Code generated by generator, DO NOT EDIT.")
	spec.sourceFile = os.Getenv("GOFILE")
	spec.pkgName = goPackage
	ext := filepath.Ext(spec.sourceFile)
	baseFilename := spec.sourceFile[0 : len(spec.sourceFile)-len(ext)]
	spec.generateFileName = baseFilename + "_gen.go"
	return &spec
}

func fromArgs(args []string) *interfaceFileSpec {
	return nil
}
