typemeta:
  kind: ""
  apiversion: ""
objectmeta:
  name: vet-service-shadow
  generatename: ""
  namespace: default
  selflink: ""
  uid: ""
  resourceversion: ""
  generation: 0
  creationtimestamp: "0001-01-01T00:00:00Z"
  deletiontimestamp: null
  deletiongraceperiodseconds: null
  labels:
    app: vets-service
    mesh.megaease.com/shadow-service: "true"
  annotations: {}
  ownerreferences: []
  finalizers: []
  clustername: ""
  managedfields: []
spec:
  replicas: 1
  selector:
    matchlabels:
      app: vets-service
      mesh.megaease.com/shadow-service: "true"
    matchexpressions: []
  template:
    objectmeta:
      name: ""
      generatename: ""
      namespace: ""
      selflink: ""
      uid: ""
      resourceversion: ""
      generation: 0
      creationtimestamp: "0001-01-01T00:00:00Z"
      deletiontimestamp: null
      deletiongraceperiodseconds: null
      labels:
        app: vets-service
        mesh.megaease.com/shadow-service: "true"
      annotations: {}
      ownerreferences: []
      finalizers: []
      clustername: ""
      managedfields: []
    spec:
      volumes:
      - name: configmap-volume-0
        volumesource:
          hostpath: null
          emptydir: null
          gcepersistentdisk: null
          awselasticblockstore: null
          gitrepo: null
          secret: null
          nfs: null
          iscsi: null
          glusterfs: null
          persistentvolumeclaim: null
          rbd: null
          flexvolume: null
          cinder: null
          cephfs: null
          flocker: null
          downwardapi: null
          fc: null
          azurefile: null
          configmap: null
          vspherevolume: null
          quobyte: null
          azuredisk: null
          photonpersistentdisk: null
          projected: null
          portworxvolume: null
          scaleio: null
          storageos: null
          csi: null
          ephemeral: null
      initcontainers: []
      containers:
      - name: vets-service
        image: megaease/spring-petclinic-vets-service:latest
        command:
        - /bin/sh
        args:
        - -c
        - java -server -Xmx1024m -Xms1024m -Dspring.profiles.active=sit -Djava.security.egd=file:/dev/./urandom  org.springframework.boot.loader.JarLauncher
        workingdir: ""
        ports:
        - name: ""
          hostport: 0
          containerport: 0
          protocol: ""
          hostip: ""
        envfrom: []
        env: []
        resources:
          limits: {}
          requests: {}
        volumemounts: []
        volumedevices: []
        livenessprobe: null
        readinessprobe: null
        startupprobe: null
        lifecycle:
          poststart: null
          prestop: null
        terminationmessagepath: ""
        terminationmessagepolicy: ""
        imagepullpolicy: ""
        securitycontext: null
        stdin: false
        stdinonce: false
        tty: false
      - name: ""
        image: ""
        command: []
        args: []
        workingdir: ""
        ports: []
        envfrom: []
        env:
        - name: EASE_KAFKA_SHADOW_CONFIG
          value: '{"Hosts":["a","bbb"]}'
          valuefrom: null
        resources:
          limits: {}
          requests: {}
        volumemounts: []
        volumedevices: []
        livenessprobe: null
        readinessprobe: null
        startupprobe: null
        lifecycle: null
        terminationmessagepath: ""
        terminationmessagepolicy: ""
        imagepullpolicy: ""
        securitycontext: null
        stdin: false
        stdinonce: false
        tty: false
      ephemeralcontainers: []
      restartpolicy: ""
      terminationgraceperiodseconds: null
      activedeadlineseconds: null
      dnspolicy: ""
      nodeselector: {}
      serviceaccountname: ""
      deprecatedserviceaccount: ""
      automountserviceaccounttoken: null
      nodename: ""
      hostnetwork: false
      hostpid: false
      hostipc: false
      shareprocessnamespace: null
      securitycontext: null
      imagepullsecrets: []
      hostname: ""
      subdomain: ""
      affinity: null
      schedulername: ""
      tolerations: []
      hostaliases: []
      priorityclassname: ""
      priority: null
      dnsconfig: null
      readinessgates: []
      runtimeclassname: null
      enableservicelinks: null
      preemptionpolicy: null
      overhead: {}
      topologyspreadconstraints: []
      sethostnameasfqdn: null
  strategy:
    type: ""
    rollingupdate: null
  minreadyseconds: 0
  revisionhistorylimit: null
  paused: false
  progressdeadlineseconds: null
status:
  observedgeneration: 0
  replicas: 0
  updatedreplicas: 0
  readyreplicas: 0
  availablereplicas: 0
  unavailablereplicas: 0
  conditions: []
  collisioncount: null
