/*
Copyright (c) 2017, MegaEase
All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// code generated by github.com/megaease/easemeshctl/cmd/generator, DO NOT EDIT.
package meshclient

import (
	"context"
	"encoding/json"
	"fmt"
	v1alpha1 "github.com/megaease/easemesh-api/v1alpha1"
	resource "github.com/megaease/easemeshctl/cmd/client/resource"
	client "github.com/megaease/easemeshctl/cmd/common/client"
	errors "github.com/pkg/errors"
	"net/http"
)

type loadbalanceGetter struct {
	client *meshClient
}
type loadBalanceInterface struct {
	client *meshClient
}

func (l *loadbalanceGetter) LoadBalance() LoadBalanceInterface {
	return &loadBalanceInterface{client: l.client}
}
func (l *loadBalanceInterface) Get(args_0 context.Context, args_1 string) (*resource.LoadBalance, error) {
	url := fmt.Sprintf("http://"+l.client.server+apiURL+"/mesh/services/%s/"+"LoadBalance", args_1)
	r, err := client.NewHTTPJSON().GetByContext(args_0, url, nil, nil).HandleResponse(func(b []byte, statusCode int) (interface{}, error) {
		if statusCode == http.StatusNotFound {
			return nil, errors.Wrapf(NotFoundError, "get LoadBalance %s", args_1)
		}
		if statusCode >= 300 {
			return nil, errors.Errorf("call %s failed, return status code %d text %+v", url, statusCode, b)
		}
		LoadBalance := &v1alpha1.LoadBalance{}
		err := json.Unmarshal(b, LoadBalance)
		if err != nil {
			return nil, errors.Wrapf(err, "unmarshal data to v1alpha1.LoadBalance")
		}
		return resource.ToLoadBalance(args_1, LoadBalance), nil
	})
	if err != nil {
		return nil, err
	}
	return r.(*resource.LoadBalance), nil
}
func (l *loadBalanceInterface) Patch(args_0 context.Context, args_1 *resource.LoadBalance) error {
	url := fmt.Sprintf("http://"+l.client.server+apiURL+"/mesh/services/%s/"+"LoadBalance", args_1)
	object := args_1.ToV1Alpha1()
	_, err := client.NewHTTPJSON().PutByContext(args_0, url, object, nil).HandleResponse(func(b []byte, statusCode int) (interface{}, error) {
		if statusCode == http.StatusNotFound {
			return nil, errors.Wrapf(NotFoundError, "patch LoadBalance %s", args_1.Name())
		}
		if statusCode < 300 && statusCode >= 200 {
			return nil, nil
		}
		return nil, errors.Errorf("call PUT %s failed, return statuscode %d text %+v", url, statusCode, b)
	})
	return err
}
func (l *loadBalanceInterface) Create(args_0 context.Context, args_1 *resource.LoadBalance) error {
	url := fmt.Sprintf("http://"+l.client.server+apiURL+"/mesh/services/%s/"+"LoadBalance", args_1)
	_, err := client.NewHTTPJSON().PostByContext(args_0, url, nil, nil).HandleResponse(func(b []byte, statusCode int) (interface{}, error) {
		if statusCode == http.StatusConflict {
			return nil, errors.Wrapf(ConflictError, "create LoadBalance %s", args_1.Name())
		}
		if statusCode < 300 && statusCode >= 200 {
			return nil, nil
		}
		return nil, errors.Errorf("call Post %s failed, return statuscode %d text %+v", url, statusCode, b)
	})
	return err
}
func (l *loadBalanceInterface) Delete(args_0 context.Context, args_1 string) error {
	url := fmt.Sprintf("http://"+l.client.server+apiURL+"/mesh/services/%s/"+"LoadBalance", args_1)
	_, err := client.NewHTTPJSON().DeleteByContext(args_0, url, nil, nil).HandleResponse(func(b []byte, statusCode int) (interface{}, error) {
		if statusCode == http.StatusNotFound {
			return nil, errors.Wrapf(NotFoundError, "Delete LoadBalance %s", args_1)
		}
		if statusCode < 300 && statusCode >= 200 {
			return nil, nil
		}
		return nil, errors.Errorf("call Delete %s failed, return statuscode %d text %+v", url, statusCode, b)
	})
	return err
}
func (l *loadBalanceInterface) List(args_0 context.Context) ([]*resource.LoadBalance, error) {
	url := "http://" + l.client.server + apiURL + "/mesh/services"
	result, err := client.NewHTTPJSON().GetByContext(args_0, url, nil, nil).HandleResponse(func(b []byte, statusCode int) (interface{}, error) {
		if statusCode == http.StatusNotFound {
			return nil, errors.Wrapf(NotFoundError, "list service")
		}
		if statusCode >= 300 && statusCode < 200 {
			return nil, errors.Errorf("call GET %s failed, return statuscode %d text %+v", url, statusCode, b)
		}
		services := []v1alpha1.Service{}
		err := json.Unmarshal(b, &services)
		if err != nil {
			return nil, errors.Wrapf(err, "unmarshal data to v1alpha1.")
		}
		results := []*resource.LoadBalance{}
		for _, service := range services {
			if service.LoadBalance != nil {
				results = append(results, resource.ToLoadBalance(service.Name, service.LoadBalance))
			}
		}
		return results, nil
	})
	if err != nil {
		return nil, err
	}
	return result.([]*resource.LoadBalance), nil
}
